--Create table brand (brand_id int,name varchar(50));

--Insert INTO brand (brand_id,name)
Values
    (1,'Kia'),
    (2,'Bmw'),
    (3,'Volvo'),
    (4,'Nissan'),
    (5,'Chevrolet'),
    (6,'Audi'),
    (7,'Ford'),
    (8,'Hyundai'),
    (9,'Buick'),
    (10,'Cadillac'),
    (11,'Acura'),
    (12,'Lexus'),
    (13,'Infiniti'),
    (14,'Jeep'),
    (15,'Mercedes-Benz'),
    (16,'Mitsubishi'),
    (17,'Mazda'),
    (18,'Mini'),
    (19,'Land Rover'),
    (20,'Lincoln'),
    (21,'Jaguar'),
    (22,'Volkswagen'),
    (23,'Toyota'),
    (24,'Subaru'),
    (25,'Scion'),
    (26,'Porsche'),
    (27,'Dodge'),
    (28,'Fiat'),
    (29,'Chrysler'),
    (30,'Ferrari'),
    (31,'Honda'),
    (32,'Gmc'),
    (33,'Ram'),
    (34,'Smart'),
    (35,'Bentley'),
    (36,'Pontiac'),
    (37,'Saturn'),
    (38,'Maserati'),
    (39,'Mercury'),
    (40,'Hummer'),
    (41,'Landrover'),
    (42,'Mercedes'),
    (43,'Gmc Truck'),
    (44,'Saab'),
    (45,'Suzuki'),
    (46,'Oldsmobile'),
    (47,'Isuzu'),
    (48,'Dodge Tk'),
    (49,'Geo'),
    (50,'Rolls-Royce'),
    (51,'Mazda Tk'),
    (52,'Hyundai Tk'),
    (53,'Mercedes-B'),
    (54,'Vw'),
    (55,'Daewoo'),
    (56,'Chev Truck'),
    (57,'Ford Tk'),
    (58,'Plymouth'),
    (59,'Ford Truck'),
    (60,'Tesla'),
    (61,'Airstream'),
    (62,'Dot'),
    (63,'Aston Martin'),
    (64,'Fisker'),
    (65,'Lamborghini'),
    (66,'Lotus');
